### ISSUE TITLE
Plugin does not autopost

### ISSUE THREAD

**Issue by eksopolitiikka** [pfefferle/wordpress-share-on-bluesky#2]
Hi,

installed the plugin from zip and put in my application instance, username and password. Everything seems to go fine. But the plugin does not do anything. I have articles queued up and new ones are posted every day. I should see these posted to bsky if the plugin is to be functional normally, right?

I can provide logs if needed. Running Wordpress 6.3

**Comment by morphtown** [comment]
Same here.

**Comment by pfefferle** [comment]
Sadly Bluesky changed the API a lot lately. I will check the plugin again, the next days.

**Comment by morphtown** [comment]
Will it need the application password one created for the plugin then?

**Comment by eksopolitiikka** [comment]
thank you

seems fairly straightforward, at least these examples here: https://atproto.com/blog/create-post

**Comment by pfefferle** [comment]
This should be fixed now. Please re-check and re-open if not.
