### ISSUE TITLE
Error connecting instance

### ISSUE THREAD

**Issue by morphtown** [pfefferle/wordpress-share-on-bluesky#3]
After updating the plugin I get an error message ...

> There was an error connecting to your Bluesky instance. Please check your credentials.

Probably related to WP version 6.3 ?

`¯\_(ツ)_/¯`

**Comment by MindFMM** [comment]
Unfortunately have the same problem.

¯\_(ツ)_/¯

**Comment by pfefferle** [comment]
is this still an issue? can you try to install the latest version and re-test?
