### ISSUE TITLE
Loses authentication?

### ISSUE THREAD

**Issue by gloriousnoise** [pfefferle/wordpress-share-on-bluesky#4]
Had it working. But then the next day it didn't work. I re-entered my app password and then updated a post and it posted to Bluesky.

**Comment by pfefferle** [comment]
Yes, it seems that Blueskys code has an expiry time and I have not yet implemented a refresh.

**Comment by gloriousnoise** [comment]
I see in the code it looks like there's already something to refresh it weekly.

`
/**
 * Add a weekly event to refresh the access token.
 *
 * @return void
 */
function add_scheduler() {
	if ( ! \wp_next_scheduled( 'bluesky_refresh_token' ) ) {
		\wp_schedule_event( time(), 'weekly', 'bluesky_refresh_token' );
	}
}
\register_activation_hook( __FILE__, __NAMESPACE__ . '\add_scheduler' );
`

Can I just tweak that to daily? Or hourly or whatever?

**Comment by pfefferle** [comment]
sure! https://developer.wordpress.org/reference/functions/wp_get_schedules/#source

**Comment by gloriousnoise** [comment]
Cool. I changed it to twicedaily. Fingers crossed! Thanks!

**Comment by pfefferle** [comment]
I just had a look! This is only the scheduler, I have not yet implemented the listener, that refreshes the token 🫣 (shame on me).

I hope I will find some time next week, to work on that!

**Comment by gloriousnoise** [comment]
Is there harm in re-authenticating before each post?

**Comment by pfefferle** [comment]
this should be fixed now! please re-open if not!
